spring:
  application:
    name: backend
  cache: # Cache hinzugefügt art jCache mit Caffeine
    type: jcache
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - bucket4j-login-cache
      - bucket4j-signup-cache
      - bucket4j-analytics-cache

  datasource:
    url: jdbc:sqlite:/app/data/app.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      connection-init-sql: "PRAGMA foreign_keys = ON"

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    show-sql: false


cors:
  allowed-origins: https://terzenbach.com

server:
  port: 8080
  forward-headers-strategy: native

logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: WARN


bucket4j:
  enabled: true
  filters:
    - name: loginFilter                # ab v0.13 Pflicht, frei wählbar
      cache-name: bucket4j-login-cache # muss mit deinem CacheConfig übereinstimmen
      url: '^/api/auth/login$'         # RegEx für deinen Login-Endpoint
      filter-method: servlet           # Standard-Filter-Typ
      http-status-code: TOO_MANY_REQUESTS
      strategy: first                  # bei mehreren Limits: nur das erste anwenden
      rate-limits:
        - bandwidths:
            - capacity: 5
              refill-capacity: 5
              time: 1
              unit: minutes
              refill-speed: interval

    - name: signupFilter
      cache-name: bucket4j-signup-cache
      url: '^/api/auth/signup$'
      filter-method: servlet
      http-status-code: TOO_MANY_REQUESTS
      strategy: first
      rate-limits:
        - bandwidths:
            - capacity: 10
              refill-capacity: 10
              time: 1
              unit: minutes
              refill-speed: interval

    - name: analyticsFilter
      cache-name: bucket4j-analytics-cache
      url: '^/api/analytics/track$'
      filter-method: servlet
      http-status-code: TOO_MANY_REQUESTS
      strategy: first
      rate-limits:
        - bandwidths:
            - capacity: 60
              refill-capacity: 60
              time: 1
              unit: minutes
              refill-speed: interval

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
