CREATE TABLE IF NOT EXISTS MEAL (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mealName TEXT NOT NULL,
    mealDescription TEXT,
    calories INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  passwordHash TEXT NOT NULL,
  role TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FEEDBACK(
id  INTEGER PRIMARY KEY AUTOINCREMENT,
feedback TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS page_visits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  visited_at DATETIME DEFAULT CURRENT_TIMESTAMP
);