CREATE TABLE IF NOT EXISTS MEAL (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mealName TEXT NOT NULL,
    mealDescription TEXT,
    imageID INTEGER 
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  passwordHash TEXT NOT NULL
);